### ISSUE TITLE
关于标定中 avia2imu和mid70toimu

### ISSUE THREAD

**Issue by lyfadvance** [kafeiyin00/WHU-HelmetDataset#2]
我看calibration目录中提供了两种激光雷达相对于imu的外参。想问一下数据集里面用的是avia2imu还是mid70toimu?

**Comment by kafeiyin00** [comment]
![image](https://github.com/kafeiyin00/WHU-HelmetDataset/assets/10334862/a3296faf-1079-43f3-91b3-8c78f152ea90)

可以参考scanner type 判断

**Comment by lyfadvance** [comment]
好的，谢谢了。
