### ISSUE TITLE
Baiduyun 

### ISSUE THREAD

**Issue by chengwei0427** [kafeiyin00/WHU-HelmetDataset#3]
Hi， @kafeiyin00 
Nice work!
But the data is hard to download, can you provide a BaiduYun link?

**Comment by kafeiyin00** [comment]
Hi, @chengwei0427 

Here is the link to BaiduYun.
链接：https://pan.baidu.com/s/1hhSTDHYGYKpVQfyUJWycwg?pwd=re8z 
提取码：re8z 

Regards.

Jianping
