### ISSUE TITLE
How to extract the datasets?

### ISSUE THREAD

**Issue by patripfr** [kafeiyin00/WHU-HelmetDataset#4]
Hi,
thanks for providing this large dataset :)
I successfully used "5.1_Heritage_library_2021-11-10-16-03-20.bag", however I fail to extract the bags from the remaining files, specifially the 7z.001 / 7z.002. I tried 7zip, but I can't get a .bag file out of it.
Could you please provide some instructions on how to extract the bag files?
Thanks,
Patrick

**Comment by kafeiyin00** [comment]
Hi Patrik,

You can put *7z.001,*7z.002 in one folder, and then unzip *7z.001. You can get the full bag file.

Best regards.

Jianping.

**Comment by patripfr** [comment]
Turns out some of my files got corrupted during download and that's why it didnt work. Downloaded again now and it worked, thanks :)

**Comment by Freeskylover** [comment]
> Turns out some of my files got corrupted during download and that's why it didnt work. Downloaded again now and it worked, thanks :)

i get same problem,but only one file can be unzipped using 7zip in windows 11, so i think some files is corrupted, i choose redownloading.
