### ISSUE TITLE
请问rosrun报错怎么解决

### ISSUE THREAD

**Issue by 1098469287** [kafeiyin00/WHU-HelmetDataset#5]
rosrun my_cpp_package rosbag_edit
/home/wendy/wuda/bag/4_Infrustracture_2021-11-14-09-18-30.bag /home/wendy/wuda/result

terminate called after throwing an instance of 'rosbag::BagIOException' what): Error opening file: /home/wendy/wuda/result
一开始第一个文件地址没有具体到bag也报错了 修改之后报了第二个地址的错

**Comment by kafeiyin00** [comment]
rosbag play 是否有问题

**Comment by 1098469287** [comment]
> rosbag play 是否有问题
rosbag play 没有问题

**Comment by whw-create** [comment]
> rosbag play 是否有问题

为什么没把gt直接放出来呢，发了邮件没人回复~~~

**Comment by kafeiyin00** [comment]
@whw-create 没有收到署名邮件，需要统计使用情况。

**Comment by kafeiyin00** [comment]
@1098469287 rosbag_edit 只是数据格式转换。如果rosbag play 没问题，请检查环境配置。

**Comment by kafeiyin00** [comment]
> > rosbag play 是否有问题
> > rosbag play 没有问题

https://github.com/kafeiyin00/FAST_LIO/blob/main/dataset/rosbag_edit.cpp 可以参考这个项目配置。我这里运行没有问题

**Comment by kafeiyin00** [comment]
命令如下：
rosrun fast_lio rosbag_edit /media/iot/JianpingData/WHU_Helmet/6.1_roadside_campus_2021-11-12-10-10-57.bag /media/iot/JianpingData/WHU_Helmet/6.1_roadside_campus_2021-11-12-10-10-57_fastl
io.bag

> > > rosbag play 是否有问题
> > > rosbag play 没有问题
> 
> https://github.com/kafeiyin00/FAST_LIO/blob/main/dataset/rosbag_edit.cpp 可以参考这个项目配置。我这里运行没有问题
