### ISSUE TITLE
Helmet dataset failed for fast-lio

### ISSUE THREAD

**Issue by yangtseJin** [kafeiyin00/WHU-HelmetDataset#6]
在跑fast-lio时，如果直接使用Heltet数据集，会导致严重的漂移，如下图所示
我使用的是Heltet数据集提供的配置文件
请问是还有其他参数需要调试吗

When running fast-lio, if I use the Heltet dataset directly, it will cause serious drift, as shown in the figure below. 
I am using the configuration file provided by the Heltet dataset. 
Are there other parameters that need to be set?
![Selection_835](https://github.com/user-attachments/assets/9dc3ef69-d95f-4642-b5e6-a34eb6c56fda)

**Comment by wwtinwhu** [comment]
有使用[rosbag_edit](https://github.com/kafeiyin00/WHU-HelmetDataset/blob/main/rosbag_edit.cpp) 对原始bag做一个处理吗？

**Comment by yangtseJin** [comment]
> 有使用[rosbag_edit](https://github.com/kafeiyin00/WHU-HelmetDataset/blob/main/rosbag_edit.cpp) 对原始bag做一个处理吗？ 详情见这里 https://github.com/kafeiyin00/WHU-HelmetDataset?tab=readme-ov-file#28-run-dataset

谢谢，我使用这个代码处理之后可以正常跑fast-lio
